name: publish-package.yml

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:

      - name: Set VERSION variable from tag or fallback
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "VERSION=0.0.1-preview" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }} --no-restore

      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build

      - name: Push
        run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate

      - name: Push Symbols
        run: dotnet nuget push **\*.snupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate